### ISSUE TITLE
Topic not specified in notification request is legit

### ISSUE THREAD

**Issue by PaulBernier** [andris9/pubsubhubbub#5]
Hello,

At line 331 there is this block: 
```javascript
    if (!topic) {
        return this._sendError(req, res, next, 400, 'Bad Request');
    }
```
Meaning if the request doesn't have a 'topic' parameter the notification is failed. But I don't see in the spec: https://pubsubhubbub.googlecode.com/git/pubsubhubbub-core-0.4.html#contentdistribution where this parameter is required. Could you explain this if condition please?

**Comment by andris9** [comment]
`topic` value is parsed form the `link` http header (see [here](https://github.com/andris9/pubsubhubbub/blob/master/src/pubsubhubbub.js#L318-L323)) where rel=topic and rel=hub entries are mandatory by 0.4
