### ISSUE TITLE
hub.lease_seconds

### ISSUE THREAD

**Issue by Feverqwe** [andris9/pubsubhubbub#7]
Hello! How I can add in subscribe form "hub.lease_seconds"?

Google PubSubHubbub Hub support it https://pubsubhubbub.appspot.com/

**Comment by ivanm376** [comment]
fork project / add "hub.lease_seconds" parameter
https://github.com/andris9/pubsubhubbub/blob/8758d4ff26df84f2e78a3076c72aa7a7e32004b3/src/pubsubhubbub.js#L149

**Comment by andris9** [comment]
Added `leaseSeconds` option on v1.0.1
